### ISSUE TITLE
NullPointerException caused by StringSplitterMapper

### ISSUE THREAD

**Issue by ST2Labs** [wizzie-io/normalizer#42]
Now, When Starting get the following error:

```
11:37:28 ERROR [org.apa.kaf.str.pro.int.AssignedStreamsTasks] stream-thread [normalizer_normalizer-StreamThread-1] Failed to process stream task 0_1 due to the following error:
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       sasl.mechanism = GSSAPI
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       security.protocol = PLAINTEXT
kafka_normalizer.2.snkbrxwvb5qe@wk03    | java.lang.NullPointerException: null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at java.lang.String.split(String.java:2337) ~[?:1.8.0_181]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       send.buffer.bytes = 131072
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at io.wizzie.normalizer.funcs.impl.StringSplitterMapper.process(StringSplitterMapper.java:38) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       session.timeout.ms = 10000
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at io.wizzie.normalizer.funcs.impl.StringSplitterMapper.process(StringSplitterMapper.java:14) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.cipher.suites = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at io.wizzie.normalizer.funcs.MapperFunction.apply(MapperFunction.java:37) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at io.wizzie.normalizer.funcs.MapperFunction.apply(MapperFunction.java:14) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.endpoint.identification.algorithm = https
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:41) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.key.password = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.keymanager.algorithm = SunX509
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.keystore.location = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.keystore.password = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.kstream.internals.KStreamFlatMap$KStreamFlatMapProcessor.process(KStreamFlatMap.java:42) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.keystore.type = JKS
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.protocol = TLS
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.provider = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.secure.random.implementation = null
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.trustmanager.algorithm = PKIX
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.truststore.location = null
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.truststore.password = null
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       ssl.truststore.type = JKS
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129) ~[kafka-streams-2.1.0.jar:?]
kafka_normalizer.1.yo8f0t0hmhnz@wk05    |       value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
kafka_normalizer.2.snkbrxwvb5qe@wk03    |       at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93) ~[kafka-streams-2.1.0.jar:?]
```

**Comment by pablocasares** [comment]
Hello again, Julian.

I see that you have two normalizer instances. 
At the logs I see: "base-functions-0.7.2-SNAPSHOT.jar". That means you are using version master. 
We recommend you to use the current latest release (0.7.1) instead of version master in your production environments.
Please checkout to 0.7.1 and compile that version.

Ensure both Normalizers are running with the same versions if you are using them clustered. 

This is not the reason of your issue but this will improve the stability of your deployments. 

After this, your NullPointerException is probably caused because StringSplitterMapper is receiving the String like this {"myString":null}. The String received by this function can not be null. 

You can avoid this situation using some of our functions. The desired behaviour depends on your use case but I'll show you some examples that you could use:

1. Filter that message with {"myString":null}

use a filter function before StringSplitterMapper function:

```
{
  "name": "myFieldFilter",
  "className": "io.wizzie.normalizer.funcs.impl.FieldFilter",
  "properties": {
    "dimension": "myString",
    "value": null,
    "__MATCH": false
  }
}
```
https://wizzie-io.github.io/normalizer/functions/filter_functions#fieldfilter


2. Replace null value to ""

``` 
       {
          "name": "myReplaceMapper",
          "className": "io.wizzie.normalizer.funcs.impl.ReplaceMapper",
          "properties": {
            "replacements":[
              {
                "dimension": "myString",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              }
            ]
          }
        }
```

Also, to check what is StringSplitterMapper receiving, you can use LogMapper function.
https://wizzie-io.github.io/normalizer/functions/debug_functions#logmapper

This function will print the message it receives to the log so you can check if you have a "string":null or not.

I hope this helps.

So, as your choice depends on your use case. If you need more help, please describe me what you need to do with some examples and then I will suggest you the best solution.

**Comment by ST2Labs** [comment]
Now I have this error, I can't understand, because Kafka is PARTITION by defatult (TIME).

```
 2018-12-13 12:59:49 INFO [io.wiz.nor.fun.imp.deb.LogMapper] KEY: null - VALUE: {id=MyDevice, sn=DHEHTSKS, time=2018-12-13 12:18:36 UTC}
kafka_normalizer.1.w0vmkxo7636b@wk04    | 2018-12-13 12:59:49 ERROR [org.apa.kaf.str.pro.int.AssignedStreamsTasks] stream-thread [normalizer_normalizer-StreamThread-1] Failed to process stream task 0_2 due to the following error:
kafka_normalizer.1.w0vmkxo7636b@wk04    | java.lang.NullPointerException: null

```

**Comment by pablocasares** [comment]
First of all, your issue isn't related to the null Key. Normalizer will just send to the output the same key the message had when it received it.

In order to help you, can you please post here your StreamPlan (just the part where you define the StringSplitterMapper). This will let me to know what you want to do. Also please post here the entire error trace. 

Thank you!

**Comment by pablocasares** [comment]
If you need to repartition your stream with a new key based on some field like:

key - message

null - {"myField1": "foo", "myField2": "bar"}

And you want to repartition it like:

bar - {"myField1": "foo", "myField2": "bar"}

you just have to define a streamplan with a sink like this:

```
        "sinks":[
            {"topic":"myPartitionedStream", "partitionBy":"myField2"}
        ]
```

This will create a new internal stream (don't will be produced to kafka) with keys equals to "myField2" values. 

If you want to repartition the stream and send it to kafka you should use this instead:
```
        "sinks":[
            {"topic":"myPartitionedStream", "type":"kafka", "partitionBy":"myField2"}
        ]
```
That will repartition your stream and send it to "myPartitionedStream" kafka topic. 

You can read more about this here:

https://wizzie-io.github.io/normalizer/configuration/stream_configuration#sinks

**Comment by pablocasares** [comment]
And, what do you mean by "Kafka is PARTITION by default (TIME)"? LogMapper shows that your message doesn't have a key. Please consume from your input topic and check messages are keyed.

**Comment by ST2Labs** [comment]
Yes, I think .. I know !.. Thanks, Kafka doesnt have a key, the problem is other... I check stream.json because I migrate from 0.5.x to 0.7.x han there is breaking change !

**Comment by pablocasares** [comment]
👍 post here your StringSplitterMapper definition if you need more help. Please tell me if you have solved your issue.

**Comment by ST2Labs** [comment]
Here:

{
          "name":"split-cat",
          "className":"io.wizzie.normalizer.funcs.impl.StringSplitterMapper",
          "properties": {
            "dimension": "cat",
            "delimiter": "\s",
            "fields": ["cat", "cat_signature"],
            "delete_dimension": false
          }
        },
I want to:

cat="A Bsignature" > cat=A cat_signature=Bsignature

Thanks

**Comment by ST2Labs** [comment]
I dont know ....

Stream.json

{
          "name": "AvoidNullReplaceMapper",
          "className": "io.wizzie.normalizer.funcs.impl.ReplaceMapper",
          "properties": {
            "replacements":[
              {
                "dimension": "msg",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              },
              {
                "dimension": "arg",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              },
              {
                "dimension": "cat",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              }
            ]
          }
        },
 ....  < Here other funcs > .... 
         {
          "name":"split-arg",
          "className":"io.wizzie.normalizer.funcs.impl.StringSplitterMapper",
          "properties": {
            "dimension": "arg",
            "delimiter": " code=",
            "fields": ["arg", "code"],
            "delete_dimension": false
          }
        },


```
java.lang.NullPointerException: null
kafka_normalizertest.1.r09djmvnlamm@wk06    |   at java.lang.String.split(String.java:2337) ~[?:1.8.0_181]
kafka_normalizertest.1.r09djmvnlamm@wk06    |   at io.wizzie.normalizer.funcs.impl.StringSplitterMapper.process(StringSplitterMapper.java:38) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizertest.1.r09djmvnlamm@wk06    |   at io.wizzie.normalizer.funcs.impl.StringSplitterMapper.process(StringSplitterMapper.java:14) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizertest.1.r09djmvnlamm@wk06    |   at io.wizzie.normalizer.funcs.MapperFunction.apply(MapperFunction.java:37) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
kafka_normalizertest.1.r09djmvnlamm@wk06    |   at io.wizzie.normalizer.funcs.MapperFunction.apply(MapperFunction.java:14) ~[base-functions-0.7.2-SNAPSHOT.jar:?]
```

**Comment by ST2Labs** [comment]
The problem is:

`cat="catsig=Bsignature"` > I want to:

```
Split with delimiter: "catsig=" Then I have NullPointer.
```

Thanks.

**Comment by ST2Labs** [comment]
Hi, 

I update StringSplitterMapper:

I'm going to avoid doing split, if data == null ! 

```
if (data != null) {
                    String [] tokens = data.split(delimiter, fieldNames.size());

                    for(int i = 0; i < tokens.length; i++)
                        value.put(fieldNames.get(i), tokens[i].trim());
                }                
```

**Comment by pablocasares** [comment]
Data shouldn't be null at that point that's because we don't need to filter that case. Put a LogMapper before your StringSplitterMapper and post here your results. Data should not be null because you did this:

``` 
{
          "name": "AvoidNullReplaceMapper",
          "className": "io.wizzie.normalizer.funcs.impl.ReplaceMapper",
          "properties": {
            "replacements":[
              {
                "dimension": "msg",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              },
              {
                "dimension": "arg",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              },
              {
                "dimension": "cat",
                "replacements": [
                  {"from": null, "to": ""}
                ]
              }
            ]
          }
        }
```
So, after this function, all of your fields should be empty strings instead of nulls.

**Comment by ST2Labs** [comment]
I find problems, 

I have found  error in stream.json definitions with StringSplitterMapper >>> "delimitier" and "delimiter".

I review and update and now running ! without NullPointer 

Thanks ...

**Comment by pablocasares** [comment]
I'm glad to hear that 👍 Thank you too!
